<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net8.0;net9.0;net10.0</TargetFrameworks>
    <ToolCommandName>dotnet-fm-generator</ToolCommandName>
    <PackAsTool>true</PackAsTool>
    <OutputType>Exe</OutputType>
    <Description>.NET Core CLI tool for generating FluentMigrator migration classes from existing databases</Description>
  </PropertyGroup>
  <Import Project="$(MSBuildThisFileDirectory)../../PackageTool.props" />
  <ItemGroup>
    <PackageReference Include="McMaster.Extensions.CommandLineUtils" Version="4.1.1" />
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="9.0.7" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="9.0.7" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\FluentMigrator.MigrationGenerator\FluentMigrator.MigrationGenerator.csproj" />
  </ItemGroup>
</Project>
