on:
  pull_request:
    branches:
    - '*'
    
env:
  solution: 'FluentMigrator.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: Release
  FM_TestConnectionStrings__SqlServer2016__ContainerEnabled: true
  FM_TestConnectionStrings__SqlServer2016__IsEnabled: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.11
      with:
        versionSpec: 5.x
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        clean: true
    - name: Install GitVersion (using GitTools 0.10.2.23031113 or later)
      uses: gittools/actions/gitversion/setup@v0.9.11
      with:
        versionSpec: 5.12
        includePrerelease: true
    - name: Execute GitVersion (using GitTools 0.10.2.23031113 or later)
      uses: gittools/actions/gitversion/execute@v0.9.11
      env:
        BUILD_BUILDNUMBER: ${{ env.GitVersion.NuGetVersionV2 }}
      with:
        updateAssemblyInfo: false
    - run: dotnet restore ${{ env.solution }}
    - run: dotnet build '${{ env.solution }}' --no-restore --property:configuration='${{ env.buildConfiguration }}' --property:platform='${{ env.buildPlatform }}' --property:Version="${{ github.run_number }}"
    - name: Setup VSTest Path
      uses: darenm/Setup-VSTest@v1.3
  
    - name: VSTest
      run: |
        dotnet tool install --global coverlet.console
        dotnet test test\FluentMigrator.Tests\bin\${{ env.buildConfiguration }}\net48\FluentMigrator.Tests.dll --collect:"XPlat Code Coverage;Format=opencover"
      shell: powershell
    - uses: actions/upload-artifact@v4
      with:
        path: ${{ github.workspace }}
        name: drop
